#!/usr/bin/python
import subprocess
#subprocess.run("python -m unittest",shell=True)
files = ["test_stateFollowingHO_ttns.py", "test_stateFollowingHO.py",
        "test_lanczosLINDEP.py", "test_lanczosBlockTTNS.py",
        "test_lanczosBlock.py", "test_feast_fortran.py",
        "test_lanczosTTNS.py", "test_lanczos.py","test_feast.py"]
for item in files:
    subprocess.run("python "+item,shell=True)
